# database container
db:
    image: postgres:latest
    environment:
        POSTGRES_USER: evething
        POSTGRES_PASSWORD: evething
    # Expose for debugging/remote connection
    ports:
        - "5432:5432"
# redis container
redis:
    image: redis:latest
    # Expose redis port
    ports:
        - "6379:6379"
# container with Django dev server
django:
    build: .
    dockerfile: docker/Dockerfile-dev
    command: /evething/docker/devserver.sh
    volumes:
        - .:/evething  # mount current directory inside container
    ports:
        - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
        - db:db
        - redis:redis
# container with celery worker
celery:
    image: evething_django
    command: /evething/docker/worker-dev.sh
    volumes_from:
        - django
    links:
        - db:db
        - redis:redis
